import type { Locale } from "./locale";

export const auditMessages = {
  skill_request: ["Skill request", "技能请求"], plugin_trial: ["Plugin trial", "插件试运行"], approval_action: ["Approval operation", "审批操作"], knowledge_change: ["Knowledge-library change", "知识库变更"], ticket_read: ["Ticket read", "工单读取"], connector_sync: ["Connector sync", "连接器同步"],
  completed: ["Completed", "已完成"], partial: ["Partially completed", "部分完成"], no_result: ["No available result", "无可用结果"], waiting_confirmation: ["Awaiting confirmation", "待确认"], waiting_approval: ["Approval process", "审批流程"], needs_input: ["Input required", "待补充"], not_found: ["Not found", "未找到"], no_evidence: ["Insufficient evidence", "资料不足"], not_routed: ["Not matched", "未匹配"], unavailable: ["Not connected", "未接入"], failed: ["Execution failed", "执行失败"], denied: ["Access denied", "拒绝访问"], invalid_request: ["Invalid request", "请求无效"], pending: ["Awaiting approval", "待审批"], approved: ["Approved", "已通过"], rejected: ["Rejected", "已驳回"], cancelled: ["Withdrawn", "已撤回"], expired: ["Expired", "已过期"], executing: ["Executing", "执行中"], execution_unknown: ["Outcome requires reconciliation", "结果待核对"], draft: ["Draft", "草稿"], published: ["Published", "已发布"], inactive: ["Inactive", "已停用"], indexing: ["Indexing", "索引处理中"], error: ["Operation error", "操作错误"], incomplete: ["Not finalized", "未收尾"],
  skill: ["Skill", "技能"], plugin: ["Plugin", "插件"], approval: ["Approval", "审批"], ticket: ["Ticket", "工单"], document: ["Document", "资料"], source: ["Citation source", "引用来源"], policy: ["Policy", "策略"], connector: ["Connector", "连接器"], connector_source: ["Connector source", "连接器来源"], security_review: ["Security Review", "安全审查"],
  title: ["Audit Records", "审计记录"], refresh: ["Refresh audit", "刷新审计"], scope: ["Current identity scope", "当前身份范围"], order: ["Newest start first", "开始时间倒序"], loaded: ["Loaded", "已加载"], more: ["More available", "还有更多"], metadataOnly: ["Operation metadata only", "仅含操作元数据"], locate: ["Find audit by ID", "按编号查审计"], id: ["Audit ID", "审计编号"], locateAction: ["Locate audit record", "定位审计记录"], clear: ["Clear related-record filter", "清除关联筛选"], search: ["Search loaded audit records", "搜索已加载审计"], searchHint: ["Request ID, operation or related ID", "请求编号、操作或关联编号"], kind: ["Audit type", "审计类型"], allKinds: ["All types", "全部类型"], status: ["Audit outcome status", "审计结果状态"], allStatuses: ["All outcomes", "全部结果"], loading: ["Loading persistent audit records", "正在读取持久审计"], list: ["Audit list", "审计列表"], caption: ["Persistent execution audit for the current identity", "当前身份的持久执行审计"], action: ["Operation", "操作"], outcome: ["Outcome", "结果"], startedAt: ["Started", "开始时间"], duration: ["Duration", "耗时"], empty: ["No matching loaded audit records", "没有符合条件的已加载审计"], next: ["Load next page", "继续读取下一页"], detail: ["Audit details", "审计详情"], download: ["Download audit JSON", "下载审计 JSON"], mutation: ["May change business state", "可能变更业务状态"], read: ["Read or preview", "读取或预览"], incompleteNotice: ["Only the start record was saved. The audit does not confirm the business outcome; this does not mean the business operation failed.", "仅保存了开始记录。业务结果尚未在审计中确认，不代表业务失败。"],
  requestId: ["Request ID", "请求编号"], trace: ["Request chain", "请求链"], sameChain: ["View this request chain", "查看同链记录"], identity: ["Identity", "身份"], development: ["Shared DEV identity", "DEV 共享身份"], entra: ["Entra identity", "Entra 身份"], permissions: ["Permissions for this record", "当前记录权限"], completedAt: ["Completed", "完成时间"], durationHttp: ["Duration / HTTP", "耗时 / HTTP"], errorCode: ["Error code", "错误码"], parent: ["Previous audit record", "前一条审计"], references: ["Related objects & versions", "关联对象与版本"], viewReference: ["View related", "查看关联"], filterReference: ["Filter related audit", "筛选关联审计"], input: ["Input summary", "输入摘要"], queryLength: ["Request characters", "请求字符数"], contentLength: ["Document characters", "文档字符数"], fields: ["Parameter fields", "参数字段"], none: ["None", "无"], impact: ["Impact", "影响范围"], confirmed: ["Confirmation flag", "确认标记"], queryHash: ["Request SHA-256", "请求 SHA-256"], contentHash: ["Document SHA-256", "文档 SHA-256"], executionTrace: ["Execution trace", "执行轨迹"], original: ["Original audit JSON", "审计原始 JSON"], detailLoading: ["Loading audit details", "正在读取审计详情"], noDetail: ["No audit details", "暂无审计详情"],
  errorAccess: ["The current identity cannot access these audit records.", "当前身份无权查看审计记录。"], errorNotFound: ["No accessible audit record was found for the current identity.", "未找到当前身份可访问的审计记录。"], errorFilter: ["The audit filter format is invalid.", "审计筛选格式无效。"], errorId: ["Enter a complete, valid audit ID.", "请输入完整有效的审计编号。"], errorUnavailable: ["Audit records are unavailable. Refresh to check their state.", "审计记录暂不可用，请刷新核对状态。"],
} as const satisfies Record<string, readonly [string, string]>;
export type AuditTextKey = keyof typeof auditMessages;
export function auditText(locale: Locale, key: AuditTextKey) { return auditMessages[key][locale === "zh-CN" ? 1 : 0]; }
export function auditErrorKey(code: unknown): AuditTextKey {
  if (code === "AUTHENTICATION_REQUIRED" || code === "PERMISSION_REQUIRED") return "errorAccess";
  if (code === "NOT_FOUND") return "errorNotFound";
  if (code === "INVALID_REQUEST") return "errorFilter";
  return "errorUnavailable";
}
export class AuditReadFailure extends Error { constructor(public key: AuditTextKey) { super(key); } }