import type { Locale } from "./locale";

export const connectorMessages = {
  title: ["Connectors", "连接器"], refresh: ["Refresh sources", "刷新来源"], initialize: ["Initialize synthetic sources", "初始化模拟来源"], configuration: ["Blob connector configuration", "Blob 连接器配置"], name: ["Azure Blob Document Sync", "Azure Blob 资料同步"], connection: ["Connection", "连接方式"], identity: ["Existing managed identity · Private Blob", "现有托管身份 · 私有 Blob"], scope: ["Source scope", "来源范围"], target: ["Target", "目标"], draftTarget: ["Synthetic knowledge library · Draft", "模拟知识库 · 草稿"], config: ["Configuration", "配置"], configured: ["Source configured", "来源已配置"], notConfigured: ["Not configured", "未配置"], loading: ["Loading", "读取中"],
  seedConfirm: ["Confirm synthetic source initialization", "初始化模拟来源确认"], seedWarning: ["Add missing built-in synthetic templates under the configured source prefix. Existing files remain unchanged.", "将在指定来源前缀补齐内置模拟范本，已有文件保持不变。"], seeding: ["Initializing", "初始化中"], seedAction: ["Confirm initialization", "确认初始化"], seedCancel: ["Cancel initialization", "取消初始化"], createdCount: ["Created", "新增"], existingCount: ["Retained", "保留"], failedCount: ["Failed", "失败"],
  search: ["Search connector sources", "搜索连接器来源"], searchHint: ["Source, document number or title", "来源、文号或标题"], changeFilter: ["Filter source differences", "来源差异筛选"], allChanges: ["All differences", "全部差异"], area: ["Connector business area", "连接器业务领域"], reset: ["Reset source filters", "重置来源筛选"], loadingSources: ["Loading sources and differences", "正在读取来源与差异"], sourceList: ["Connector source list", "连接器来源列表"], caption: ["Synthetic documents under the fixed Blob prefix", "固定 Blob 前缀下的模拟资料"], sourceDocument: ["Source document", "来源资料"], difference: ["Difference", "差异"], sync: ["Sync", "同步"], manifestUnread: ["Manifest not read", "清单未读取"],
  new: ["New source", "新来源"], changed: ["Source updated", "来源已更新"], unchanged: ["Content unchanged", "内容一致"], unavailable: ["Source unavailable", "来源不可用"], syncing: ["Syncing", "同步中"], syncError: ["Failed", "失败"], idle: ["Recorded", "已记录"], notSynced: ["Not synced", "未同步"], noMatches: ["No matching sources", "没有符合条件的来源"], noSources: ["No readable source manifests", "尚无可读取的来源清单"], loadMore: ["Load more sources", "继续读取来源"], detail: ["Connector source details", "连接器来源详情"], synthetic: ["Chengchuan Digital · Synthetic material", "澄川数科 · 模拟资料"], contentFile: ["Content file", "正文文件"], modifiedAt: ["Source modified", "来源修改时间"], verifySync: ["Verify and sync", "核对并同步"], syncDraft: ["Sync as draft", "同步为草稿"], openLibrary: ["Open knowledge library", "打开知识库"], linkedDocument: ["Linked document", "对应资料"],
  syncConfirm: ["Confirm connector sync", "连接器同步确认"], reuseWarning: ["Reuse the document for this source version, retaining its current publication status.", "将复用此来源版本对应的资料，保留当前发布状态。"], syncWarning: ["Import this source version as a draft without publishing it automatically. Existing documents remain unchanged.", "将此来源版本导入为草稿，不自动发布；已有资料保持不变。"], syncAction: ["Confirm sync", "确认同步"], syncCancel: ["Cancel sync", "取消同步"], previousDocument: ["View previous synced document", "查看上次同步资料"], detailViews: ["Source detail views", "来源详情视图"], preview: ["Content & chunks", "正文与分块"], versions: ["Version comparison", "版本对比"], history: ["Sync history", "同步记录"], noContent: ["No verifiable source content is available.", "当前没有可验证的来源正文。"], fingerprint: ["Source fingerprint", "来源指纹"], lastFingerprint: ["Last synced fingerprint", "上次同步指纹"], noSuccess: ["No successful sync recorded", "尚无成功记录"], lastSuccess: ["Last successful sync", "上次成功时间"], notAvailable: ["Unavailable", "不可用"], contentHash: ["Content SHA-256", "正文 SHA-256"], manifestEtag: ["Manifest ETag", "清单 ETag"], contentEtag: ["Content ETag", "正文 ETag"], targetId: ["Target ID", "目标编号"], manifestJson: ["Original source manifest JSON", "来源清单 JSON"], startedAt: ["Sync in progress · Started", "同步进行中 · 开始于"], unknown: ["Unknown", "未知"], noHistory: ["No completed sync records", "暂无已完成的同步记录"], created: ["Draft imported", "已导入草稿"], reused: ["Document reused", "已复用资料"], failed: ["Sync failed", "同步失败"], detailLoading: ["Loading source details", "正在读取来源详情"], noDetail: ["No source details", "暂无来源详情"],
  SOURCE_NOT_FOUND: ["The source file was removed. Imported documents remain unchanged.", "来源文件已移除，已导入资料保持不变。"], SOURCE_CHANGED: ["The source version changed. Refresh and verify it again.", "来源版本已变化，请刷新后重新核对。"], SOURCE_CONTENT_MISMATCH: ["Content does not match the manifest SHA-256; it has not been imported.", "正文与清单中的 SHA-256 不一致，尚未导入。"], SOURCE_TOO_LARGE: ["The source file exceeds the import size limit.", "来源文件超过本次导入大小限制。"], INVALID_SOURCE_UTF8: ["The source is not valid UTF-8 text.", "来源文件不是有效的 UTF-8 文本。"], INVALID_SOURCE_MANIFEST: ["The manifest does not match the synthetic knowledge format.", "来源清单不符合模拟知识资料格式。"], INVALID_SOURCE_TEXT: ["Source content does not meet knowledge-library import requirements.", "来源正文不符合知识库导入要求。"], INVALID_SOURCE_PATH: ["The source ID or filename is invalid.", "来源标识或文件名无效。"],
  SYNC_CONFLICT: ["Another operation updated the sync state. Refresh before retrying.", "同步状态已被另一操作更新，请刷新后重试。"], SYNC_BUSY: ["Sync is still running. Refresh to recover after an interruption of two minutes.", "同步仍在进行；中断两分钟后可刷新并恢复。"], SYNC_INTERRUPTED: ["The previous sync did not finish. Recovery records are retained.", "上次同步未完成，已保留恢复记录。"], SYNC_TARGET_CONFLICT: ["The target differs from the source snapshot. Existing content was not overwritten.", "目标资料与来源快照不一致，未覆盖已有资料。"], SYNC_DRAFT_UNCONFIRMED: ["Draft saving is unconfirmed. After refreshing, retrying reuses the same target ID.", "本次草稿保存结果未确认。刷新后重试将复用同一目标编号。"], SYNC_RECORD_UNAVAILABLE: ["The sync record is unconfirmed. Refresh before deciding whether to retry.", "同步记录未确认，请刷新状态后再决定是否重试。"], INVALID_SYNC_RECORD: ["The stored sync record violates its contract; the operation cannot continue.", "保存的同步记录不符合契约，暂不能继续。"], CONNECTOR_NOT_CONFIGURED: ["Blob sources are not configured in this environment.", "当前环境尚未配置 Blob 来源。"], CONNECTOR_STORAGE_UNAVAILABLE: ["Blob sources are unavailable. Refresh later.", "Blob 来源暂不可用，请稍后刷新。"], EXAMPLE_SOURCE_CONFLICT: ["An existing synthetic template has different content. Source files were not overwritten.", "模拟范本已有不同正文，未覆盖源文件。"], EXAMPLE_SOURCE_UNAVAILABLE: ["Synthetic source initialization is incomplete. Existing files remain unchanged.", "模拟来源初始化未完成，已存在的文件保持不变。"], AUDIT_START_FAILED: ["The audit start record was not saved; no sync write was made.", "审计开始记录未能保存，本次未进行同步写入。"], DEV_MANAGEMENT_REQUIRED: ["Sync requires explicit shared-identity DEV mode.", "同步仅在显式 DEV 共享身份模式开放。"], PERMISSION_REQUIRED: ["The current identity lacks knowledge-document permissions.", "当前身份没有知识资料权限。"], AUTHENTICATION_REQUIRED: ["This request requires sign-in.", "当前请求需要登录。"], INVALID_REQUEST: ["The sync request format is invalid.", "同步请求格式不符合要求。"],
  requestFailure: ["The connector outcome is unavailable or unconfirmed. Refresh source and sync state.", "连接器暂不可用或结果未确认，请刷新来源与同步状态。"], invalidResult: ["The sync result is invalid. Refresh to verify the outcome.", "返回的同步结果无效，请刷新核对。"], timeout: ["The sync result has not arrived. Refresh to reconcile it; the same source version does not create duplicate documents.", "同步结果尚未返回，请刷新核对。相同来源版本不会重复创建资料。"],
} as const satisfies Record<string, readonly [string, string]>;
export type ConnectorTextKey = keyof typeof connectorMessages;
export function connectorText(locale: Locale, key: ConnectorTextKey) { return connectorMessages[key][locale === "zh-CN" ? 1 : 0]; }
export const connectorErrorCodes = ["SOURCE_NOT_FOUND", "SOURCE_CHANGED", "SOURCE_CONTENT_MISMATCH", "SOURCE_TOO_LARGE", "INVALID_SOURCE_UTF8", "INVALID_SOURCE_MANIFEST", "INVALID_SOURCE_TEXT", "INVALID_SOURCE_PATH", "SYNC_CONFLICT", "SYNC_BUSY", "SYNC_INTERRUPTED", "SYNC_TARGET_CONFLICT", "SYNC_DRAFT_UNCONFIRMED", "SYNC_RECORD_UNAVAILABLE", "INVALID_SYNC_RECORD", "CONNECTOR_NOT_CONFIGURED", "CONNECTOR_STORAGE_UNAVAILABLE", "EXAMPLE_SOURCE_CONFLICT", "EXAMPLE_SOURCE_UNAVAILABLE", "AUDIT_START_FAILED", "DEV_MANAGEMENT_REQUIRED", "PERMISSION_REQUIRED", "AUTHENTICATION_REQUIRED", "INVALID_REQUEST"] as const satisfies readonly ConnectorTextKey[];
export function connectorErrorKey(code: unknown): ConnectorTextKey { return connectorErrorCodes.find((known) => known === code) ?? "requestFailure"; }
export class ConnectorRequestFailure extends Error { constructor(public key: ConnectorTextKey) { super(key); } }