import type { Locale } from "./locale";

export const libraryMessages = {
  title: ["Knowledge Library", "知识库"], refresh: ["Refresh documents", "刷新资料"], import: ["Import document", "导入资料"], simulation: ["Chengchuan Digital · Synthetic knowledge library", "澄川数科 · 模拟知识库"], builtinCount: ["built-in documents", "份内置资料"], importedCount: ["imported documents loaded", "份导入资料已加载"], more: ["More available", "还有更多"], management: ["DEV management mode", "DEV 管理模式"], readOnly: ["Read-only mode", "只读模式"],
  search: ["Search knowledge documents", "搜索知识资料"], searchHint: ["Title, document number or responsible department", "标题、文号或责任部门"], origin: ["Document origin", "资料来源"], allOrigins: ["All origins", "全部来源"], builtin: ["Built in", "内置资料"], imported: ["Imported", "导入资料"], status: ["Publication status", "资料发布状态"], allStatuses: ["All statuses", "全部状态"], area: ["Business area", "业务领域"], allAreas: ["All areas", "全部领域"],
  "search-company-policy": ["HR policies", "人事制度"], "search-expense-policy": ["Travel & expenses", "差旅报销"], "search-procurement-guide": ["Procurement", "采购流程"], "search-security-guidance": ["Information security", "信息安全"], "search-software-catalog": ["Software services", "软件服务"],
  draft: ["Draft", "草稿"], indexing: ["Indexing", "索引处理中"], published: ["Published", "已发布"], inactive: ["Inactive", "已停用"], error: ["Publication failed", "发布失败"], loading: ["Loading documents", "正在加载资料"], list: ["Knowledge document list", "知识资料列表"], caption: ["Knowledge documents and publication status", "知识库资料和发布状态"], document: ["Document", "资料"], chunks: ["Chunks", "片段"], noMatches: ["No matching documents", "没有符合条件的资料"], loadMore: ["Load more imported documents", "加载更多导入资料"], detail: ["Knowledge document details", "知识资料详情"], synthetic: ["Synthetic material", "模拟资料"], version: ["Version", "版本"], blobSource: ["Blob synchronization source", "Blob 同步来源"], sourceHistory: ["View source and synchronization history", "查看来源与同步记录"], owner: ["Responsible department", "责任部门"], snapshotDate: ["Snapshot date", "快照日期"], effectiveDate: ["Effective date", "生效日期"], filename: ["File", "文件"], characters: ["characters", "字符"],
  retryPublish: ["Retry publication", "重试发布"], reindex: ["Reindex", "重新索引"], publish: ["Publish to index", "发布索引"], deactivate: ["Deactivate document", "停用资料"], retrievalTest: ["Test retrieval", "检索测试"], confirmGroup: ["Confirm document operation", "资料操作确认"], publishWarning: ["Publish all chunks of this document for DEV knowledge retrieval.", "将发布此资料的全部片段，供 DEV 知识问答检索。"], deactivateWarning: ["Deactivate this document and exclude it from answer citations. Original text and draft records are retained.", "将停用此资料并从问答引用中排除，原文和草稿记录保留。"], confirmPublish: ["Confirm publication", "确认发布"], confirmDeactivate: ["Confirm deactivation", "确认停用"], processing: ["Processing", "处理中"], cancelAction: ["Cancel document operation", "取消资料操作"], contentViews: ["Document content views", "资料内容视图"], source: ["Original text", "原文"], chunkPreview: ["Chunk preview", "分块预览"], sourceLink: ["Original citation text", "引用原文"], detailLoading: ["Loading document", "正在读取资料"], noDetail: ["No document details", "暂无资料详情"],
  importTitle: ["Import synthetic document", "导入模拟资料"], importLabel: ["Import knowledge document", "导入知识资料"], cancelImport: ["Cancel import", "取消导入"], documentTitle: ["Document title", "文档标题"], documentNumber: ["Synthetic document number", "模拟文号"], documentDate: ["Document date", "资料日期"], dataKind: ["Document type", "资料类型"], policy: ["Synthetic policy", "模拟制度"], snapshot: ["Fixed business snapshot", "固定业务快照"], fileInput: ["UTF-8 file (.txt / .md)", "UTF-8 文件 (.txt / .md)"], upload: ["Upload knowledge file", "上传知识文件"], content: ["Document body", "文档正文"], simulatedCheck: ["Chengchuan Digital synthetic material, without real personal, customer or credential information", "澄川数科模拟资料，不含真实个人、客户或凭据信息"], template: ["Load original synthetic template", "载入模拟范本"], preview: ["Preview chunks", "预览分块"], save: ["Save draft", "保存草稿"], importPreview: ["Imported chunk preview", "导入分块预览"], range: ["Range", "范围"],
  fileInvalid: ["Select a UTF-8 .txt or .md file no larger than 160 KB.", "请选择不超过 160 KB 的 UTF-8 .txt 或 .md 文件。"], contentTooLong: ["Document body is limited to 48000 characters.", "文档正文最多 48000 字符。"], fileReadFailed: ["The file could not be read as valid UTF-8 text.", "文件无法读取为有效 UTF-8 文本。"], fieldsInvalid: ["Provide a title, document number, responsible department, valid date and at least 10 body characters, and confirm the synthetic-material declaration.", "请填写标题、文号、责任部门、有效日期和至少 10 字符的正文，并确认模拟资料标识。"], invalidResponse: ["The returned document state is invalid. Refresh to verify the outcome.", "返回的文档状态无效，请刷新核对结果。"], unavailable: ["The knowledge-library outcome is unavailable or unconfirmed. Refresh the record before retrying.", "知识库结果不可用或未确认，请刷新核对记录后再重试。"],
  AUDIT_START_FAILED: ["The audit start record was not saved; no document was written or modified.", "审计开始记录未保存，本次未写入或修改资料。"], INVALID_REQUEST: ["Document content or fields do not meet the requirements.", "文档内容或字段格式不符合要求。"], DOCUMENT_TOO_LARGE: ["The document exceeds the import size limit.", "文档超过导入大小限制。"], DEV_MANAGEMENT_REQUIRED: ["Read-only mode. Management operations require explicit DEV test mode.", "当前为只读模式，管理操作仅在显式 DEV 测试模式开放。"], PERMISSION_REQUIRED: ["The current identity cannot access the knowledge library.", "当前身份没有知识库访问权限。"], AUTHENTICATION_REQUIRED: ["This request requires sign-in.", "当前请求需要登录。"], CONFLICT: ["Another operation changed the document state. Refresh before retrying.", "资料状态已被其他操作更新，请刷新后重试。"], BUSY: ["Indexing is still in progress. Refresh the state; interrupted tasks can be retried after two minutes.", "索引操作仍在进行，请刷新状态；中断任务可在两分钟后重试。"], INDEX_PUBLISH_FAILED: ["Index publication failed. The draft is retained and can be retried.", "索引发布失败，草稿已保留，可以重试。"], INDEX_CLEANUP_FAILED: ["The document is inactive, but index cleanup failed. Deactivate again to retry cleanup.", "文档已停用，但索引清理失败，可以再次停用以重试清理。"], NOT_FOUND: ["The document does not exist or was removed.", "文档不存在或已移除。"],
} as const satisfies Record<string, readonly [string, string]>;

export type LibraryTextKey = keyof typeof libraryMessages;
export function libraryText(locale: Locale, key: LibraryTextKey) { return libraryMessages[key][locale === "zh-CN" ? 1 : 0]; }
export function libraryErrorKey(code: unknown): LibraryTextKey {
  return code === "AUDIT_START_FAILED" || code === "INVALID_REQUEST" || code === "DOCUMENT_TOO_LARGE" || code === "DEV_MANAGEMENT_REQUIRED" || code === "PERMISSION_REQUIRED" || code === "AUTHENTICATION_REQUIRED" || code === "CONFLICT" || code === "BUSY" || code === "INDEX_PUBLISH_FAILED" || code === "INDEX_CLEANUP_FAILED" || code === "NOT_FOUND" ? code : "unavailable";
}
export class LibraryRequestFailure extends Error {
  constructor(public key: LibraryTextKey) { super(key); }
}