import type { Locale } from "./locale";

export const pluginMessages = {
  title: ["Plugin Catalog", "插件目录"], details: ["Plugin details", "插件详情"], registered: ["Built in · Registered", "内置 · 已注册"], contract: ["Contract", "契约"], operation: ["Operation", "操作"], operationSelect: ["Plugin operation", "插件操作"], writeConfirmation: ["Write · Workbench confirmation", "写入 · 工作台确认"], readOnly: ["Read-only operation", "只读操作"], detailViews: ["Plugin detail views", "插件详情视图"],
  trial: ["Trial", "试运行"], contractTab: ["Input/output contract", "输入输出契约"], dependencies: ["Dependencies", "依赖配置"], permissions: ["Permissions", "权限"], location: ["Execution location", "运行位置"], inProcess: ["Application process", "应用进程内"], skills: ["Bound Skills", "绑定技能"], resultTypes: ["Result types", "结果类型"], inputSchema: ["Input JSON Schema", "输入 JSON Schema"], outputSchema: ["Output JSON Schema", "输出 JSON Schema"], dependencyStatus: ["Plugin dependency configuration", "插件依赖配置状态"], dependency: ["Dependency", "依赖"], configuration: ["Configuration", "配置"], connectivity: ["Connectivity", "连通性"], present: ["Set", "已设置"], absent: ["Not set", "未设置"], configured: ["Configuration complete", "配置齐全"], missing: ["Configuration missing", "缺少配置"], notProbed: ["Not probed", "未探测"],
  refresh: ["Refresh Plugins", "刷新插件"], loading: ["Loading", "加载中"], builtin: ["built-in Plugins", "内置插件"], operations: ["visible operations", "可见操作"], simulation: ["DEV · Synthetic business data", "DEV · 模拟业务"], search: ["Search Plugins", "搜索插件"], searchHint: ["Plugin, operation, Skill or permission", "插件、操作、技能或权限"], effectFilter: ["Filter Plugin operation type", "插件操作类型"], allOperations: ["All operations", "全部操作"], read: ["Read operations", "读取操作"], write: ["Write preview", "写入预览"], configFilter: ["Filter Plugin configuration", "插件配置状态"], allConfigs: ["All configuration states", "全部配置状态"], reset: ["Reset Plugin filters", "重置插件筛选"], catalogLoading: ["Loading Plugin catalog", "正在读取插件目录"], list: ["Built-in Plugin list", "内置插件列表"], plugins: ["Plugins", "插件"], noMatches: ["No matching Plugins", "没有符合条件的插件"], noPlugins: ["No Plugins available for this identity", "当前身份没有可用插件"], updated: ["Updated", "更新于"], detailLoading: ["Loading Plugin definition", "正在加载插件定义"], noDetails: ["No Plugin details", "暂无插件详情"],
  catalogAccess: ["The current identity cannot access the Plugin catalog.", "当前身份无权查看插件目录。"], catalogFailure: ["The Plugin catalog could not be loaded.", "插件目录加载失败。"], catalogInvalid: ["The Plugin catalog response did not match its contract.", "插件目录数据格式不符合预期。"],
  savedLoad: ["Load saved tickets", "读取已保存工单"], savedLabel: ["Saved DEV receipts", "已保存的 DEV 回执"], savedSelect: ["Saved DEV tickets", "已保存的 DEV 工单"], chooseTicket: ["Select a ticket", "选择工单"], noSaved: ["No saved tickets", "暂无已保存工单"], unspecifiedDevice: ["Device not specified", "未指定设备"], savedFailure: ["Saved tickets are unavailable. Refresh later or enter an ID manually.", "已保存工单暂不可用，可稍后刷新或手动输入编号。"],
  status_completed: ["Completed", "已完成"], status_needs_input: ["Input required", "待补充"], status_no_evidence: ["Insufficient evidence", "资料不足"], status_not_found: ["Ticket not found", "未找到工单"], status_waiting_confirmation: ["Awaiting workbench confirmation", "待工作台确认"], status_failed: ["Execution failed", "执行失败"],
  AUTHENTICATION_REQUIRED: ["This request requires sign-in.", "当前请求需要登录。"], PERMISSION_REQUIRED: ["The current identity cannot trial this operation.", "当前身份无权试运行此操作。"], SUBJECT_REQUIRED: ["The current identity has no ticket owner identifier.", "当前身份缺少工单所属人标识。"], OPERATION_SKILL_MISMATCH: ["The operation/Skill binding changed. Refresh the Plugin catalog.", "操作与技能绑定已变化，请刷新插件目录。"], PLUGIN_OPERATION_NOT_FOUND: ["The Plugin or operation was not found. Refresh the catalog.", "插件或操作不存在，请刷新目录。"], INVALID_REQUEST: ["Input does not match this operation's contract.", "输入不符合该操作契约。"], REQUEST_TOO_LARGE: ["Trial input exceeds the size limit.", "试运行输入超过大小限制。"],
  trialFailure: ["The trial outcome is unconfirmed. Check the audit record before retrying.", "试运行结果未确认，请先核对审计后再重试。"], mismatch: ["The service returned a mismatched trial result.", "服务返回了不匹配的试运行结果。"], invalidStatus: ["The service did not return a confirmed execution status.", "服务未返回可确认的执行状态。"], timeout: ["The trial timed out; no confirmed result was received.", "试运行超时，本次未得到可确认的结果。"], cancelled: ["Stopped receiving this trial's response. Server-side reads may still be running.", "已取消接收本次试运行结果，服务端读取可能仍在执行。"],
  result: ["Plugin trial results", "插件试运行结果"], resultHeading: ["Trial results", "试运行结果"], running: ["Trial running", "正在试运行"], noResult: ["No trial results yet", "尚无试运行结果"], noWrite: ["No write executed", "未执行写入"], actualRead: ["Actual read", "实际读取"], completedAt: ["Completed", "完成时间"], dependencyFailure: ["Dependency execution failed; no business result was returned.", "依赖服务执行失败，未返回业务结果。"], requiredInput: ["Required input:", "待补充："], preview: ["Ticket write preview", "工单写入预览"], review: ["Review in workbench", "前往工作台确认"], originalJson: ["Original result JSON", "原始结果 JSON"],
  input: ["Plugin trial input", "插件试运行输入"], readTrial: ["Read trial", "读取试运行"], boundSkill: ["Plugin-bound Skill", "插件绑定技能"], example: ["Synthetic input", "模拟输入"], exampleSelect: ["Plugin synthetic input", "插件模拟输入"], custom: ["Custom input", "自定义输入"], query: ["Plugin business request", "插件业务请求"], ticketId: ["Plugin ticket ID", "插件工单编号"], description: ["Plugin issue description", "插件问题描述"], device: ["Plugin device", "插件设备"], impact: ["Plugin impact", "插件影响范围"], generate: ["Generate write preview", "生成写入预览"], runRead: ["Run read", "运行读取"], cancel: ["Cancel trial", "取消试运行"], originals: ["Original examples and request text", "原始案例与请求内容"],
} as const satisfies Record<string, readonly [string, string]>;
export type PluginTextKey = keyof typeof pluginMessages;
export function pluginText(locale: Locale, key: PluginTextKey) { return pluginMessages[key][locale === "zh-CN" ? 1 : 0]; }
export function pluginErrorKey(code: unknown): PluginTextKey {
  return code === "AUTHENTICATION_REQUIRED" || code === "PERMISSION_REQUIRED" || code === "SUBJECT_REQUIRED" || code === "OPERATION_SKILL_MISMATCH" || code === "PLUGIN_OPERATION_NOT_FOUND" || code === "INVALID_REQUEST" || code === "REQUEST_TOO_LARGE" ? code : "trialFailure";
}