import {
  skillDefinitionSchema,
  type SkillDefinition,
} from "./contracts";

const definitions = [
  {
    id: "search-company-policy",
    name: "人事制度查询",
    description: "核对休假、考勤、人员归属与指定员工余额，区分制度与有日期的合成台账。",
    category: "knowledge",
    permissions: ["knowledge.read"],
    riskLevel: "low",
    confirmationRequired: false,
    keywords: ["休假制度", "年假", "考勤", "员工制度", "leave policy", "attendance policy"],
    version: "0.2.0",
  },
  {
    id: "search-expense-policy",
    name: "差旅与报销查询",
    description: "核对差旅标准、逐笔费用与凭证缺口，解释审批、支付、项目全周期预算及成本中心季度预算的已发生、已承诺与可用金额。",
    category: "knowledge",
    permissions: ["knowledge.read"],
    riskLevel: "low",
    confirmationRequired: false,
    keywords: ["差旅标准", "报销", "费用", "发票", "expense policy", "travel policy"],
    version: "0.1.0",
  },
  {
    id: "search-procurement-guide",
    name: "采购流程查询",
    description: "对照采购授权、供应商准入和多家报价，核对审批阻塞、订单与部分到货。",
    category: "knowledge",
    permissions: ["knowledge.read"],
    riskLevel: "low",
    confirmationRequired: false,
    keywords: ["采购流程", "供应商", "询价", "采购审批", "采购申请", "procurement", "vendor onboarding"],
    version: "0.1.0",
  },
  {
    id: "search-security-guidance",
    name: "信息安全指引",
    description: "核对数据共享、终端与访问规范，追溯演练事件的报告、响应和待办。",
    category: "knowledge",
    permissions: ["knowledge.read"],
    riskLevel: "low",
    confirmationRequired: false,
    keywords: ["信息安全", "钓鱼邮件", "数据共享", "密码规范", "security guidance", "phishing"],
    version: "0.1.0",
  },
  {
    id: "search-software-catalog",
    name: "企业软件目录",
    description: "查询企业软件、合成许可合同、受管资产和服务台快照，解释安装排队与续期条件。",
    category: "knowledge",
    permissions: ["knowledge.read"],
    riskLevel: "low",
    confirmationRequired: false,
    keywords: ["批准软件", "软件目录", "软件安装", "软件服务", "许可证", "approved software", "software catalog"],
    version: "0.1.0",
  },
  {
    id: "get-ticket-status",
    name: "工单状态查询",
    description: "查询当前用户有权访问的 IT 服务工单状态。",
    category: "query",
    permissions: ["tickets.read"],
    riskLevel: "low",
    confirmationRequired: false,
    keywords: ["工单状态", "查询工单", "ticket status", "incident status"],
    version: "0.1.0",
  },
  {
    id: "create-it-ticket",
    name: "创建 IT 工单",
    description: "按具体人员、设备、影响范围与已做排查准备请求，经确认或审批创建真实 DEV 回执。",
    category: "action",
    permissions: ["tickets.create"],
    riskLevel: "medium",
    confirmationRequired: true,
    keywords: ["创建工单", "提交工单", "报修", "create ticket", "report issue"],
    version: "0.1.0",
  },
] as const;

export const skillRegistry: SkillDefinition[] = definitions.map((definition) =>
  skillDefinitionSchema.parse(definition),
);