name: Security

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
    steps:
      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@c20e34f438d671fc35777cc9820dd7adf8252874 # v3
        with:
          languages: javascript-typescript
      - name: Analyze
        uses: github/codeql-action/analyze@c20e34f438d671fc35777cc9820dd7adf8252874 # v3
        with:
          category: /language:javascript-typescript

  secrets:
    name: Secret scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out full history
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - name: Scan Git history
        uses: gitleaks/gitleaks-action@dcedce43c6f43de0b836d1fe38946645c9c638dc # v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
